services:
  postgres:
    image: postgres:16
    container_name: customer-service-postgres
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer123
    ports:
      - "15432:5432"
    volumes:
      - customer_pg_data:/var/lib/postgresql/data

volumes:
  customer_pg_data: